# Generated by Django 2.0 on 2018-11-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_time_visit', models.DateField()),
                ('last_time_visit', models.DateField(blank=True)),
                ('friend_status', models.CharField(choices=[('0', 'Customer'), ('1', 'Friends'), ('2', 'myself')], max_length=1)),
                ('visit_times', models.IntegerField(default=1)),
                ('tokens', models.CharField(max_length=256)),
                ('location_city', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
