# Generated by Django 2.0 on 2018-12-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leavings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64)),
                ('username', models.CharField(blank=True, max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('address2', models.CharField(blank=True, max_length=512)),
                ('content', models.CharField(blank=True, max_length=4096)),
            ],
        ),
    ]
